# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "vm_test"
  config.vm.network "private_network", ip: "192.168.33.200"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    vb.memory = "4096"
    vb.cpus = 4
  end
  config.vm.network "forwarded_port", guest: 80, host: 10080
  config.vm.provision "shell" do |shell|
    shell.inline = "yum install -y python"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "../vm_test"
    ansible.playbook = "../site.yml"
  end
end
