---

roq_version: "latest"
roq_conda_channel: "unstable"

# FIXME(thraneh): prod has issues with accessing UDP traffic from Docker
femas_use_docker: false

###############
### ANSIBLE ###
###############

become_user: root

##############
### SYSTEM ###
##############

product_name: "Test"
upgrade_system: true
