# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.201"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 3
  end
  config.vm.provision "shell" do |shell|
    shell.inline = "yum install -y python"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
    ansible.groups = {
      "trading": "default",
      "roq-femas": "default",
      "roq-samples": "default",
    }
    ansible.extra_vars = {
      "become_user": "root",
    }
  end
end
