# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "vm_test"
  config.vm.network "private_network", ip: "192.168.33.200"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 8
  end
  config.vm.network "forwarded_port", guest: 80, host: 10080
  config.vm.provision "shell" do |shell|
    shell.inline = "apt-get update && apt-get install -y python"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "../vm_test"
    ansible.playbook = "../site.yml"
  end
end
