# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.201"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 3
  end
	config.vm.network "forwarded_port", guest: 80, host: 9090
  config.vm.provision "shell" do |shell|
    shell.inline = "apt-get update && apt-get install -y python"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
    ansible.groups = {
      "trading": "default",
      "roq-femas": "default",
      "roq-samples": "default",
    }
    ansible.extra_vars = {
      "become_user": "root",
      "femas_use_docker": "true",
      "collector_use_docker": "true",
    }
  end
end
