# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.201"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 4
  end
  config.vm.provision "shell" do |shell|
    shell.inline = "apt-get update && apt-get install -y python"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
    ansible.extra_vars = {
      "become_user": "root",
      "proxy_env": {
        "http_proxy": "http://mickey-mouse.com:8080",
        "https_proxy": "http://mickey-mouse.com:8080"
      },
      "wechat": {
        "corp_id": "some-corp-id",
        "to_party": "some-to-party",
        "agent_id": "some-agent-id",
        "api_secret": "some-api-secret"
      }
    }
    ansible.groups = {
      "server": "default",
      "secure": "default",
      "femas": "default"
    }
  end
end
